version: '38'
services:
  
  backend:
    build:
     context:
     dockerfile: docker/Dockerfile.backend
    ports:
     - "8080:8080"

    environment: 
      - DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres

    depends_on:
      - postgres

  frontend:
    build:
     context: .
     dockerfile : docker/Dockerfile.frontend
     args : 
      - DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres
     ports:
       - "3000:3000"

    environment:
      -DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres
     
    depends_on:
     - postgres

  ws:
    build:
    context : .
    dockerfile: docker/Dockerfile.ws

    ports:
     - "8081:8081"
    environment:
    - DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres 
    depends_on:
     -postgres:


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
   
         